-- =============================================
-- Lucky Draw: Reset & Cơ cấu giải mới (200 giải)
-- Chạy trên Supabase SQL Editor
-- =============================================

-- 1. Xóa toàn bộ kết quả quay cũ
TRUNCATE TABLE public.lucky_draw_results;

-- 2. Xóa prize pool cũ và tạo mới
TRUNCATE TABLE public.prize_pool;

INSERT INTO public.prize_pool (amount, total_qty, remaining_qty) VALUES
    (999999, 4, 4),
    (123456, 50, 50),
    (88888, 50, 50),
    (66666, 50, 50),
    (45678, 30, 30),
    (26262, 16, 16);

-- 3. Import 165 emails (upsert - không ghi đè existing, chỉ thêm mới)
INSERT INTO public.employees (email, full_name, role)
VALUES
    ('anhdv1@vnpay.vn', 'anhdv1', 'staff'),
    ('anhlv1@vnpay.vn', 'anhlv1', 'staff'),
    ('anhnhh@vnpay.vn', 'anhnhh', 'staff'),
    ('anhpd2@vnpay.vn', 'anhpd2', 'staff'),
    ('anhvh@vnpay.vn', 'anhvh', 'staff'),
    ('anhvp2@vnpay.vn', 'anhvp2', 'staff'),
    ('bachlx@vnpay.vn', 'bachlx', 'staff'),
    ('bachtcm@vnpay.vn', 'bachtcm', 'staff'),
    ('binhlv@vnpay.vn', 'binhlv', 'staff'),
    ('binhnx@vnpay.vn', 'binhnx', 'staff'),
    ('canhvx@vnpay.vn', 'canhvx', 'staff'),
    ('chiencq@vnpay.vn', 'chiencq', 'staff'),
    ('congnt@vnpay.vn', 'congnt', 'staff'),
    ('congpv@vnpay.vn', 'congpv', 'staff'),
    ('cucvtt@vnpay.vn', 'cucvtt', 'staff'),
    ('cuongvc1@vnpay.vn', 'cuongvc1', 'staff'),
    ('datnt19@vnpay.vn', 'datnt19', 'staff'),
    ('dattt4@vnpay.vn', 'dattt4', 'staff'),
    ('dont@vnpay.vn', 'dont', 'staff'),
    ('ducbph@vnpay.vn', 'ducbph', 'staff'),
    ('ducdm1@vnpay.vn', 'ducdm1', 'staff'),
    ('ducnm@vnpay.vn', 'ducnm', 'staff'),
    ('dungdtt2@vnpay.vn', 'dungdtt2', 'staff'),
    ('dungdx@vnpay.vn', 'dungdx', 'staff'),
    ('dungln@vnpay.vn', 'dungln', 'staff'),
    ('dungnba@vnpay.vn', 'dungnba', 'staff'),
    ('dungnd5@vnpay.vn', 'dungnd5', 'staff'),
    ('dungpt3@vnpay.vn', 'dungpt3', 'staff'),
    ('dungta@vnpay.vn', 'dungta', 'staff'),
    ('duongtq1@vnpay.vn', 'duongtq1', 'staff'),
    ('duyld@vnpay.vn', 'duyld', 'staff'),
    ('duynv4@vnpay.vn', 'duynv4', 'staff'),
    ('duytq1@vnpay.vn', 'duytq1', 'staff'),
    ('duyvv1@vnpay.vn', 'duyvv1', 'staff'),
    ('giangn@vnpay.vn', 'giangn', 'staff'),
    ('giangnh5@vnpay.vn', 'giangnh5', 'staff'),
    ('hainp1@vnpay.vn', 'hainp1', 'staff'),
    ('haint1@vnpay.vn', 'haint1', 'staff'),
    ('hangltt@vnpay.vn', 'hangltt', 'staff'),
    ('hienbt2@vnpay.vn', 'hienbt2', 'staff'),
    ('hienlt1@vnpay.vn', 'hienlt1', 'staff'),
    ('hieudc@vnpay.vn', 'hieudc', 'staff'),
    ('hieult4@vnpay.vn', 'hieult4', 'staff'),
    ('hieunhh@vnpay.vn', 'hieunhh', 'staff'),
    ('hieunm2@vnpay.vn', 'hieunm2', 'staff'),
    ('hieunm3@vnpay.vn', 'hieunm3', 'staff'),
    ('hinhnv@vnpay.vn', 'hinhnv', 'staff'),
    ('hoangnm5@vnpay.vn', 'hoangnm5', 'staff'),
    ('hoangvh@vnpay.vn', 'hoangvh', 'staff'),
    ('hoannc@vnpay.vn', 'hoannc', 'staff'),
    ('hoannm1@vnpay.vn', 'hoannm1', 'staff'),
    ('hoanptk@vnpay.vn', 'hoanptk', 'staff'),
    ('hoanth@vnpay.vn', 'hoanth', 'staff'),
    ('hopvn@vnpay.vn', 'hopvn', 'staff'),
    ('hunghd@vnpay.vn', 'hunghd', 'staff'),
    ('hunglk1@vnpay.vn', 'hunglk1', 'staff'),
    ('hungnq9@vnpay.vn', 'hungnq9', 'staff'),
    ('hungnt1@vnpay.vn', 'hungnt1', 'staff'),
    ('hungnt3@vnpay.vn', 'hungnt3', 'staff'),
    ('hungnv14@vnpay.vn', 'hungnv14', 'staff'),
    ('huyhq@vnpay.vn', 'huyhq', 'staff'),
    ('huynct@vnpay.vn', 'huynct', 'staff'),
    ('huynd3@vnpay.vn', 'huynd3', 'staff'),
    ('huynn2@vnpay.vn', 'huynn2', 'staff'),
    ('huynt1@vnpay.vn', 'huynt1', 'staff'),
    ('huytd1@vnpay.vn', 'huytd1', 'staff'),
    ('huytv@vnpay.vn', 'huytv', 'staff'),
    ('huyvhm@vnpay.vn', 'huyvhm', 'staff'),
    ('khaing@vnpay.vn', 'khaing', 'staff'),
    ('khanhnn6@vnpay.vn', 'khanhnn6', 'staff'),
    ('khanhpn1@vnpay.vn', 'khanhpn1', 'staff'),
    ('khoaony@vnpay.vn', 'khoaony', 'staff'),
    ('khuongpb@vnpay.vn', 'khuongpb', 'staff'),
    ('kienda@vnpay.vn', 'kienda', 'staff'),
    ('kientt2@vnpay.vn', 'kientt2', 'staff'),
    ('lichnt@vnpay.vn', 'lichnt', 'staff'),
    ('liempt@vnpay.vn', 'liempt', 'staff'),
    ('linhhn1@vnpay.vn', 'linhhn1', 'staff'),
    ('linhhp@vnpay.vn', 'linhhp', 'staff'),
    ('locbb@vnpay.vn', 'locbb', 'staff'),
    ('longncn@vnpay.vn', 'longncn', 'staff'),
    ('longth1@vnpay.vn', 'longth1', 'staff'),
    ('longvd2@vnpay.vn', 'longvd2', 'staff'),
    ('luandn1@vnpay.vn', 'luandn1', 'staff'),
    ('lytm@vnpay.vn', 'lytm', 'staff'),
    ('mainn3@vnpay.vn', 'mainn3', 'staff'),
    ('minhnt3@vnpay.vn', 'minhnt3', 'staff'),
    ('namdt1@vnpay.vn', 'namdt1', 'staff'),
    ('namtg@vnpay.vn', 'namtg', 'staff'),
    ('nghialt3@vnpay.vn', 'nghialt3', 'staff'),
    ('nghiank@vnpay.vn', 'nghiank', 'staff'),
    ('nghianv@vnpay.vn', 'nghianv', 'staff'),
    ('ngocntb2@vnpay.vn', 'ngocntb2', 'staff'),
    ('ngocntb3@vnpay.vn', 'ngocntb3', 'staff'),
    ('ngocvb2@vnpay.vn', 'ngocvb2', 'staff'),
    ('nguyenndk@vnpay.vn', 'nguyenndk', 'staff'),
    ('nhadv@vnpay.vn', 'nhadv', 'staff'),
    ('nhanlh@vnpay.vn', 'nhanlh', 'staff'),
    ('nhatnl@vnpay.vn', 'nhatnl', 'staff'),
    ('nhatpd@vnpay.vn', 'nhatpd', 'staff'),
    ('nhatpv@vnpay.vn', 'nhatpv', 'staff'),
    ('phatlt1@vnpay.vn', 'phatlt1', 'staff'),
    ('phila@vnpay.vn', 'phila', 'staff'),
    ('phongdx@vnpay.vn', 'phongdx', 'staff'),
    ('phuongvtn@vnpay.vn', 'phuongvtn', 'staff'),
    ('quandt@vnpay.vn', 'quandt', 'staff'),
    ('quanglv2@vnpay.vn', 'quanglv2', 'staff'),
    ('quangnd3@vnpay.vn', 'quangnd3', 'staff'),
    ('quangnm1@vnpay.vn', 'quangnm1', 'staff'),
    ('quangnt@vnpay.vn', 'quangnt', 'staff'),
    ('quannm2@vnpay.vn', 'quannm2', 'staff'),
    ('quinhn@vnpay.vn', 'quinhn', 'staff'),
    ('quoctv@vnpay.vn', 'quoctv', 'staff'),
    ('quynhnt2@vnpay.vn', 'quynhnt2', 'staff'),
    ('sanglq@vnpay.vn', 'sanglq', 'staff'),
    ('sonnt9@vnpay.vn', 'sonnt9', 'staff'),
    ('sylp@vnpay.vn', 'sylp', 'staff'),
    ('taind@vnpay.vn', 'taind', 'staff'),
    ('taint5@vnpay.vn', 'taint5', 'staff'),
    ('tainv1@vnpay.vn', 'tainv1', 'staff'),
    ('tanlt@vnpay.vn', 'tanlt', 'staff'),
    ('tanlv2@vnpay.vn', 'tanlv2', 'staff'),
    ('thaidv@vnpay.vn', 'thaidv', 'staff'),
    ('thalt@vnpay.vn', 'thalt', 'staff'),
    ('thangnb@vnpay.vn', 'thangnb', 'staff'),
    ('thangnd1@vnpay.vn', 'thangnd1', 'staff'),
    ('thangnh4@vnpay.vn', 'thangnh4', 'staff'),
    ('thangnq1@vnpay.vn', 'thangnq1', 'staff'),
    ('thangnv2@vnpay.vn', 'thangnv2', 'staff'),
    ('thangpa@vnpay.vn', 'thangpa', 'staff'),
    ('thanhln@vnpay.vn', 'thanhln', 'staff'),
    ('thanhnx1@vnpay.vn', 'thanhnx1', 'staff'),
    ('thanhtv2@vnpay.vn', 'thanhtv2', 'staff'),
    ('thiepnx@vnpay.vn', 'thiepnx', 'staff'),
    ('thinhlh@vnpay.vn', 'thinhlh', 'staff'),
    ('thinhnq1@vnpay.vn', 'thinhnq1', 'staff'),
    ('thongth@vnpay.vn', 'thongth', 'staff'),
    ('thuyldx@vnpay.vn', 'thuyldx', 'staff'),
    ('thuytt2@vnpay.vn', 'thuytt2', 'staff'),
    ('thuyttp@vnpay.vn', 'thuyttp', 'staff'),
    ('tiendn@vnpay.vn', 'tiendn', 'staff'),
    ('tiennt4@vnpay.vn', 'tiennt4', 'staff'),
    ('tiennx2@vnpay.vn', 'tiennx2', 'staff'),
    ('tientv3@vnpay.vn', 'tientv3', 'staff'),
    ('toanhl@vnpay.vn', 'toanhl', 'staff'),
    ('toantv2@vnpay.vn', 'toantv2', 'staff'),
    ('trilc@vnpay.vn', 'trilc', 'staff'),
    ('trongdd2@vnpay.vn', 'trongdd2', 'staff'),
    ('truongnx@vnpay.vn', 'truongnx', 'staff'),
    ('tuandm4@vnpay.vn', 'tuandm4', 'staff'),
    ('tuanhdd@vnpay.vn', 'tuanhdd', 'staff'),
    ('tuanlqd@vnpay.vn', 'tuanlqd', 'staff'),
    ('tuannd5@vnpay.vn', 'tuannd5', 'staff'),
    ('tund@vnpay.vn', 'tund', 'staff'),
    ('tund1@vnpay.vn', 'tund1', 'staff'),
    ('tungdh@vnpay.vn', 'tungdh', 'staff'),
    ('tungpt1@vnpay.vn', 'tungpt1', 'staff'),
    ('tungtt4@vnpay.vn', 'tungtt4', 'staff'),
    ('tungtt6@vnpay.vn', 'tungtt6', 'staff'),
    ('tunt2@vnpay.vn', 'tunt2', 'staff'),
    ('vietnq2@vnpay.vn', 'vietnq2', 'staff'),
    ('vietth@vnpay.vn', 'vietth', 'staff'),
    ('vipt@vnpay.vn', 'vipt', 'staff'),
    ('vynnt1@vnpay.vn', 'vynnt1', 'staff'),
    ('yenbth@vnpay.vn', 'yenbth', 'staff')
ON CONFLICT (email) DO NOTHING;

-- 4. Kiểm tra kết quả
SELECT 'prize_pool' AS table_name, COUNT(*) AS count, SUM(total_qty) AS total_prizes FROM public.prize_pool
UNION ALL
SELECT 'employees', COUNT(*), NULL FROM public.employees
UNION ALL
SELECT 'lucky_draw_results', COUNT(*), NULL FROM public.lucky_draw_results;
